#!/bin/bash

# Script de Diagnóstico Railway - ZORAH CHAT
# Como o Railway não tem SSH, use os logs do Dashboard

echo "🔍 DIAGNÓSTICO RAILWAY - ZORAH CHAT"
echo "=================================="
echo ""
echo "⚠️  O Railway NÃO tem acesso SSH direto."
echo "     Use este guia para diagnosticar pelos LOGS do Dashboard."
echo ""

echo "📋 CHECKLIST DE DIAGNÓSTICO - FRONTEND"
echo "======================================"
echo ""

echo "1️⃣  VER LOGS DO FRONTEND"
echo "   Railway → Frontend (zorahchat) → Deployments → View Logs"
echo ""
echo "   Procure por estes erros:"
echo "   ❌ 'Error: Cannot find module'"
echo "   ❌ 'ENOENT: no such file'"
echo "   ❌ 'npm ERR!'"
echo "   ❌ 'command not found'"
echo "   ❌ 'Port already in use'"
echo ""

echo "2️⃣  VERIFICAR BUILD"
echo "   Nos logs, procure:"
echo "   ✅ 'vite v7.x.x building for production...'"
echo "   ✅ '✓ XXX modules transformed'"
echo "   ✅ '✓ built in XXXms'"
echo ""
echo "   Se NÃO aparecer, o BUILD FALHOU!"
echo ""

echo "3️⃣  VERIFICAR START"
echo "   Nos logs, procure:"
echo "   ✅ 'Local:   http://localhost:XXXX'"
echo "   ✅ 'Network: use --host to expose'"
echo ""
echo "   Se NÃO aparecer, o START FALHOU!"
echo ""

echo "4️⃣  VERIFICAR CONFIGURAÇÕES"
echo "   Railway → Frontend → Settings:"
echo ""
echo "   Root Directory:  frontend  (sem /)"
echo "   Build Command:   npm run build"
echo "   Start Command:   npm start"
echo ""

echo "5️⃣  VERIFICAR VARIÁVEIS"
echo "   Railway → Frontend → Variables:"
echo ""
echo "   VITE_API_URL=https://backend-chat-zorah-faturamento-laam.up.railway.app"
echo "   VITE_WS_URL=https://backend-chat-zorah-faturamento-laam.up.railway.app"
echo ""

echo ""
echo "📋 CHECKLIST DE DIAGNÓSTICO - BACKEND"
echo "======================================"
echo ""

echo "1️⃣  VER LOGS DO BACKEND"
echo "   Railway → Backend → Deployments → View Logs"
echo ""
echo "   Procure por:"
echo "   ✅ '[DATABASE] Using database at: /app/data/database.sqlite'"
echo "   ✅ 'Database initialized.'"
echo "   ✅ 'Seeding IAAM workspace...'"
echo "   ✅ 'Server running on http://localhost:3001'"
echo ""

echo "2️⃣  VERIFICAR VOLUME"
echo "   Railway → Backend → Data/Volumes"
echo ""
echo "   Deve ter um volume:"
echo "   Mount Path: /app/data"
echo "   Size: 1GB"
echo ""
echo "   Se NÃO tiver, CRIE AGORA!"
echo ""

echo "3️⃣  VERIFICAR VARIÁVEIS"
echo "   Railway → Backend → Variables:"
echo ""
echo "   ✅ PORT=3001"
echo "   ✅ JWT_SECRET=[seu_secret]"
echo "   ✅ NODE_ENV=production"
echo "   ✅ FRONTEND_URL=https://zorahchat-zorah-faturamento-iaam.up.railway.app"
echo ""
echo "   REMOVER (se existir):"
echo "   ❌ DATABASE_PUBLIC_URL"
echo "   ❌ FRONTEND_PORT"
echo ""

echo ""
echo "🔧 SOLUÇÕES RÁPIDAS"
echo "==================="
echo ""

echo "PROBLEMA: Build do frontend falha"
echo "SOLUÇÃO: Verifique se todas as dependências estão no package.json"
echo "         Veja os logs exatos do erro de build"
echo ""

echo "PROBLEMA: Frontend não inicia (502)"
echo "SOLUÇÃO 1: Commit o código atualizado e redeploy"
echo "SOLUÇÃO 2: Verifique Start Command = 'npm start'"
echo "SOLUÇÃO 3: Veja logs para erro específico"
echo ""

echo "PROBLEMA: Backend não conecta ao banco"
echo "SOLUÇÃO: Adicione Volume em /app/data"
echo "         Veja logs para 'ENOENT' ou 'database not found'"
echo ""

echo "PROBLEMA: CORS error"
echo "SOLUÇÃO: Verifique FRONTEND_URL no backend"
echo "         Deve ser a URL COMPLETA do frontend"
echo ""

echo ""
echo "⚡ AÇÕES IMEDIATAS"
echo "=================="
echo ""

echo "1. Commit código atualizado:"
echo "   git add ."
echo "   git commit -m 'Corrigir porta do frontend'"
echo "   git push"
echo ""

echo "2. Railway → Frontend → Redeploy"
echo ""

echo "3. Railway → Backend → Redeploy"
echo ""

echo "4. Aguardar 2-3 minutos"
echo ""

echo "5. Verificar logs novamente"
echo ""

echo ""
echo "📞 COMO OBTER AJUDA"
echo "==================="
echo ""

echo "Se ainda não funcionar, me envie:"
echo ""
echo "1. Screenshot dos LOGS do Frontend (últimas 50 linhas)"
echo "2. Screenshot dos LOGS do Backend (últimas 50 linhas)"
echo "3. Screenshot das VARIÁVEIS do Frontend"
echo "4. Screenshot das VARIÁVEIS do Backend"
echo "5. Screenshot da configuração de VOLUMES do Backend"
echo ""

echo "Com essas informações, posso diagnosticar exatamente o problema!"
echo ""

echo "=================================="
echo "Diagnóstico completo!"
echo "Siga os passos acima e me avise."
echo "=================================="
