const { Client } = require('pg');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

async function initPostgres() {
    console.log('--- INICIALIZANDO POSTGRESQL ---');

    // Tenta pegar a URL do ambiente, ou dos argumentos
    const connectionString = process.env.DATABASE_URL || process.argv[2];

    if (!connectionString) {
        console.error('❌ ERRO: DATABASE_URL não encontrada!');
        console.error('Certifique-se de que a variável DATABASE_URL está definida no Railway.');
        console.error('Ou execute: node scripts/init_postgres.js "postgresql://..."');
        process.exit(1);
    }

    console.log(`🔌 Conectando ao Banco... (URL mascarada: ${connectionString.split('@')[1] || '...'})`);

    const client = new Client({
        connectionString,
        ssl: { rejectUnauthorized: false }
    });

    try {
        await client.connect();
        console.log('✅ Conectado com sucesso!');

        console.log('🔨 Criando tabelas...');

        // --- TABELAS ---

        // Users
        await client.query(`
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                name TEXT NOT NULL,
                email TEXT UNIQUE NOT NULL,
                password TEXT NOT NULL,
                avatar_url TEXT,
                status TEXT DEFAULT 'online',
                status_message TEXT,
                last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        `);
        console.log('- Tabela Users OK');

        // Workspaces
        await client.query(`
            CREATE TABLE IF NOT EXISTS workspaces (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                name TEXT NOT NULL,
                slug TEXT UNIQUE NOT NULL,
                description TEXT,
                avatar_url TEXT,
                owner_id INTEGER NOT NULL REFERENCES users(id),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        `);
        console.log('- Tabela Workspaces OK');

        // Workspace Users
        await client.query(`
            CREATE TABLE IF NOT EXISTS workspace_users (
                workspace_id INTEGER NOT NULL REFERENCES workspaces(id),
                user_id INTEGER NOT NULL REFERENCES users(id),
                role TEXT DEFAULT 'member',
                permissions TEXT DEFAULT 'read,write',
                joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (workspace_id, user_id)
            );
        `);
        console.log('- Tabela Workspace Users OK');

        // Channels
        await client.query(`
            CREATE TABLE IF NOT EXISTS channels (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                workspace_id INTEGER NOT NULL REFERENCES workspaces(id),
                name TEXT NOT NULL,
                description TEXT,
                type TEXT DEFAULT 'public',
                created_by INTEGER REFERENCES users(id),
                is_default BOOLEAN DEFAULT false,
                is_private BOOLEAN DEFAULT false,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        `);
        console.log('- Tabela Channels OK');

        // Direct Messages
        await client.query(`
            CREATE TABLE IF NOT EXISTS direct_messages (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                workspace_id INTEGER NOT NULL REFERENCES workspaces(id),
                user1_id INTEGER NOT NULL REFERENCES users(id),
                user2_id INTEGER NOT NULL REFERENCES users(id),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(workspace_id, user1_id, user2_id)
            );
        `);
        console.log('- Tabela Direct Messages OK');

        // Messages
        await client.query(`
            CREATE TABLE IF NOT EXISTS messages (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                channel_id INTEGER REFERENCES channels(id),
                dm_id INTEGER REFERENCES direct_messages(id),
                user_id INTEGER NOT NULL REFERENCES users(id),
                content TEXT,
                attachment_url TEXT,
                attachment_type TEXT,
                attachment_name TEXT,
                has_mentions BOOLEAN DEFAULT false,
                file_size INTEGER,
                file_dimensions TEXT,
                edited_at TIMESTAMP,
                deleted_at TIMESTAMP,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        `);
        console.log('- Tabela Messages OK');

        // Mentions
        await client.query(`
            CREATE TABLE IF NOT EXISTS mentions (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                message_id INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(message_id, user_id)
            );
        `);
        console.log('- Tabela Mentions OK');

        // Notifications
        await client.query(`
            CREATE TABLE IF NOT EXISTS notifications (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                type TEXT NOT NULL CHECK(type IN ('dm', 'mention', 'channel_invite', 'system')),
                title TEXT NOT NULL,
                content TEXT,
                link TEXT,
                read BOOLEAN DEFAULT false,
                metadata TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        `);
        console.log('- Tabela Notifications OK');

        // Channel Members
        await client.query(`
            CREATE TABLE IF NOT EXISTS channel_members (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                channel_id INTEGER NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                added_by INTEGER NOT NULL REFERENCES users(id),
                added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(channel_id, user_id)
            );
        `);
        console.log('- Tabela Channel Members OK');

        console.log('🏁 Todas as tabelas foram verificadas/criadas!');

        // Seed Admin (Opcional, só pra garantir acesso)
        const checkAdmin = await client.query("SELECT * FROM users WHERE email = 'admin@iaam.com'");
        if (checkAdmin.rowCount === 0) {
            console.log('🌱 Criando usuário Admin padrão...');
            // Senha hashada de 'admin123'
            const hash = '$2a$10$X.v.HH/D.v.HH/D.v.HH/DeC/J.v.HH/D.v.HH/D.v.HH/D.v.HH/D';
            // Nota: O hash real precisa ser gerado pelo bcrypt, vou usar um placeholder ou inserir sem hash se for urgência, mas ideal é o app criar.
            // Vou deixar o app criar no seedDatabase() normal na próxima inicialização, ou o usuário cria no cadastro.
            console.log('⚠️ Execute o app para rodar o seed completo.');
        }

    } catch (err) {
        console.error('❌ ERRO FINAL:', err);
    } finally {
        await client.end();
    }
}

initPostgres();
